core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('property.urls', namespace='property')),
    path('agent', include('agent.urls', namespace='agent')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'pronat'

urlpatterns = [
    path('', views.properties_all, name="home_page"),
    path('properties', views.properties_list, name="properties_list"),
    path('property/<slug:slug>', views.property_detail, name = "property_detail"),
    path('apartment', views.apartment_all, name="apartment_all"),
    path('land', views.land_all, name="land_all"),
    path('garage', views.garage_all, name="garage_all"),
    path('store', views.store_all, name="store_all"),
    path('villa', views.villa_all, name="villa_all"),
    path('contact', views.contact_page,name="contact_page"),
    path('about', views.aboutus,name="aboutus"),
    path('politikat', views.politikat_privatesise,name="politkat"),
    path('zyrat', views.ofice, name="zyrat"),
    path('team',views.team, name="teams"),
]

templates/home/about.html
<!DOCTYPE html>
{% extends '../base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'core/css/about.css' %}">

{% endblock %}
{% block content %}
<div class="container">
    <h1>&nbsp;</h1>
    <h1 style="text-align:center;">About Us</h1>
    <p>&nbsp;</p>
    <p><b> Njohim tregun dhe perspektivat e zhvillimit.</b></p>
    <p>Që prej themelimit në vitin 2022, Real Estate Albania ka punuar me përkushtim dhe profesionalizëm drejt shërbimit të klientit. Këto janë vlerat që vazhdojnë të jenë ende në qendër të filozofisë tonë të biznesit. Kompania jonë falë njohjes së mirë të tregut aktual si dhe të prespektivës së zhvillimit të zonave të ndryshme është një nga hartuesit e studimit për përcaktimin e hartës së vlerës së çmimit minimal fiskal të pronësisë.

        Stafi ynë me shtrije në të tërë Shqipërinë me idetë e tij krijuese jep në çdo kohë zgjidhje fitimprurëse për pronarët, blerësit, qiramarrësit dhe investitorët duke njohur mire prioritetet e zhvillimit në projektet e qeverisë dhe institucioneve ndërkombëtare që i asistojnë në fusha si, turizmi, zona urbane, industriale etj.
        
        Edhe nëse je blerës për herë të parë, apo je vetëm një hap larg nga shtëpia e ëndrrave të tua, dëshiron të investosh në pasuri të paluajtshme, apo të krijosh biznesin tënd, Real Estate Albania ofron shërbim me zyra në çdo zonë banimi dhe kudo ku bëhen investime të reja. Të gjitha pronat janë të standarteve të larta në treg dhe kanë shtrirje në të gjitha qytetet kryesore të vendit. Ekspertiza jonë mbi legjislacionin dhe proçedurat në lidhje me çdo transkaksion të pasurive të paluajtshme e bën kompaninë tonë zgjedhjen e preferuar për çdo investitor vendas apo të huaj.
    </p>
    <p><b>Stafi Yne</b></p>
    <p>Ne zgjedhim, punesojme dhe trainojme profesionistet me te talentuar dhe me me eksperience, duke ju dhene atyre fleksibilitetin dhe strategjine kombetare qe nevojitet per t’ju shtuar vlera. Profesionistet tane tashme jane te vendosur ne te gjithe vendin, duke asistuar cdo nevoje te klientit , implementuar zgjidhje dhe duke u pershtatur me kushtet strategjike, operacionale dhe mundesine financiare te klientit. Duke punuar me nje pjestar te Kompanise sone, klienti perfiton nje larmi programesh, sherbimesh dhe metoda te krijuara specifikisht per te, duke pershtatur kerkesen dhe oferten e klienteve ne te gjithe vendin.  Per shume njerez, te blesh ose te shesesh nje prone ndoshta eshte nje nder transaksionet financiare me te medha qe ata do te bejne ne jeten e tyre. Kjo eshte arsyeja pse profesionistet e Real Estate Albania jane te perkushtuar per te drejtuar klientet ne cdo hap te transaksioneve te tyre duke tejkaluar pergjegjesite baze te nje agjenti te Pasurive te Paluajteshme.</p>
</div>
{% endblock %}

templates/home/agent_properties.html
<!DOCTYPE html>
{% extends '../base.html' %}
{%load static%}
{% block title%}Home{%endblock%}
{% block css %}<link rel="stylesheet" href="{% static 'core/css/properties.css' %}">{% endblock %}
{%block content%}

<div class="container pt-4"> 
    {% if not properties %}
    <div class="col-12">There are currently no prona active</div>
    <div>{{page.count}}</div> 
      {% else %}
        <div class="album py-5 bg-light"> 
            
         <div class="container">
         
        <div class="row">
          {% for property in page.object_list %}
          <div class="col-md-4 p-0">
            <div class="card mb-4 box-shadow row">
              {% for image in property.property_image.all %}
              {% if image.is_feature%}
              <img class="card-img-top img-fluid" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
              {% endif %}
              {% endfor %}
              <a class="text-dark text-decoration-none" href="{{ property.get_absolute_url }}">
                <div class="card-body row">
                  <div class="ps-3">
                   <p class="card-text h4 pt-3">{{  property.title|slice:":50" }}</p>
                  </div>
                  <div class="ps-2 pt-2">
                    <i class="fa-solid fa-user"></i><small class="card-text h6 ">{{user.first_name}}  {{user.last_name}}</small>
                   </div>
                  <div class="p-2">
                    <i class="fa-solid fa-location-dot"></i><small class="h6 text-muted">  {{property.address_line|slice:":40"}}</small>
                  </div>
                  <div class="p-2">
                    <div class="float-end pe-5">
                      <i class="fa-solid fa-tag"></i><small class="h5 text-muted">  {{property.price}} $</small>
                    </div>
                  </div>

                    <div class="card-footer row">
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-aspect-ratio" viewBox="0 0 16 16">
                          <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h13A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 12.5v-9zM1.5 3a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-13z"/>
                          <path d="M2 4.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1H3v2.5a.5.5 0 0 1-1 0v-3zm12 7a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1 0-1H13V8.5a.5.5 0 0 1 1 0v3z"/>
                        </svg>
                      <small>{{property.area}} m<sup>2</sup></small>
                      </div>

                      {% if property.apartment.room_num or property.apartment.room_num == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bed"></i>   
                          <small>{{ property.apartment.room_num }}</small>
                        </div>
                      
                      {% elif property.villa.room_num or property.villa.room_num == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bed"></i>   
                          <small>{{ property.villa.room_num }}</small>
                        </div>
                      {% else %}
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                        <i class="fa-solid fa-bed"></i>   
                        <small>--</small>
                      </div>
                      {% endif %}
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4" style="text-align: center;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                          <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                          <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                        </svg> <small>{{ property.views }}</small>
                      </div>
                      {% if property.apartment.bath_num == 0 or property.apartment.bath_num%}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bath"></i>  
                          <small>{{ property.apartment.bath_num }}</small>
                        </div>

                      {% elif property.store.bath_num or property.store.bath_num == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bath"></i>  
                          <small>{{ property.store.bath_num }}</small>
                        </div>
                      {% elif property.villa.bath_num or property.villa.bath_num == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bath"></i>  
                          <small>{{ property.villa.bath_num }}</small>
                        </div>
                      {% else %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bath"></i>  
                          <small>--</small>
                        </div>
                      {% endif%}
                      
                      {% if property.apartment.floor or property.apartment.floor == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-arrow-right-to-city"></i>
                          <small>{{ property.apartment.floor }}</small>
                        </div>
                      {% elif property.garage.floor or property.garage.floor == 0%}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-arrow-right-to-city"></i>
                          <small>{{ property.garage.floor }}</small>
                        </div>
                      {% elif  property.store.floor or  property.store.floor == 0%}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-arrow-right-to-city"></i>
                          <small>{{ property.store.floor }}</small>
                        </div>
                      {% else %}
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                        <i class="fa-solid fa-arrow-right-to-city"></i>
                        <small>--</small>
                      </div>
                      {% endif %}
                      
                      </div>
               </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

      </div>
        {% endif %}
      </div>
<!-- 
        <nav aria-label="...">
          <ul class="pagination">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active">
              <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#">Next</a>
            </li>
          </ul>
        </nav> -->

        
<div>
  {% load crispy_forms_tags %}
  <form class="d-flex" method="get" action="{% url "property:properties_list" %}">
    {{myFilter.form|crispy}}
    <!-- <input class="form-control me-2" name = "q" type="search" placeholder="Search" aria-label="Search"> -->
    {% comment %} <button class="btn btn-outline-success" type="submit">Search</button> {% endcomment %}
  </form>
  </div>

        <nav aria-label="...">
          <ul class="pagination">

        
          {% if page.has_previous %}
          <li class="page-item">
          <a class="page-link" href="{% url 'pronat:properties_list' %}?page={{ page.previous_page_number }}">Previous</a></li>
          {% endif %}

          {% for i in num_pages %}
          <li class="page-item">
            <a class="page-link" href="{% url 'pronat:properties_list' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
          {% endfor %}
          
          {% if page.has_next %}
          <li class="page-item">
          <a class="page-link" href="{% url 'pronat:properties_list' %}?page={{ page.next_page_number }}">Next</a></li>
          {% endif %}            
        </ul>
      </nav>

    {%endblock %}
   

templates/home/contact.html
<!DOCTYPE html>
{% extends '../base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'core/css/contact.css' %}">

{% endblock %}
{% block content %}

<section class="contact">
    <div class="content">
        <h2>Contact Us</h2>
        <p> </p>

    </div>
    <div class="container">
        <div class="contactInfo">
            <div class="box">
                <div class="icon"><i class="fas fa-map-marker-alt"></i></div>
                <div class="text">
                    <h3>Address</h3>
                    <p>Rr: “Myslym Shyri”, Tiranë</p>
                </div>
            </div>
            <div class="box">
                <div class="icon"><i class="fas fa-phone"></i></div>
                <div class="text">
                    <h3>Contact Number</h3>
                    <p>+355 67 300 5050</p>
                    
                </div>
            </div>
            <div class="box">
                <div class="icon"><i class="fas fa-envelope"></i></div>
                <div class="text">
                    <h3>Email</h3>
                    <p>info@dominusoft.co</p>
                </div>
            </div>
        </div>
        <div class="contactForm">
            <form>
                <h2>Send Message</h2>
                <div class="inputBox"> 
                    <input type="text" name="" required>
                    <span>Full Name</span>            
                </div>
                <div class="inputBox"> 
                    <input type="email" name="" required>
                    <span>Email</span>            
                </div>
                <div class="inputBox"> 
                    <textarea required></textarea>
                    <span>Message</span>            
                </div>
                <!-- Button trigger modal -->
                {% comment %} <input type="submit" > {% endcomment %}
                 <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      Submit
                 </button> 
  
  <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Success !</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                 Thank you for your feedback
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                            </div>
                        </div>
                    </div>
                 </div>
                <!-- <div class="inputBox"> 
                    <input type="submit" name="" value="Send"  >  
                           
                </div> -->
            </form>
        </div>
    </div>

</section>
{% endblock %}

templates/home/properties.html
<!DOCTYPE html>
{% extends '../base.html' %}
{%load static%}
{% block title%}Home{%endblock%}
{% block css %}<link rel="stylesheet" href="{% static 'core/css/properties.css' %}">{% endblock %}
{%block content%}

<div class="container-fluid py-5">
  {% load crispy_forms_tags %}
  <form class="d-flex justify-content-evenly" method="get" action="{% url 'pronat:properties_list' %}">
    {{myFilter.form|crispy}}
    <!-- <input class="form-control me-2" name = "q" type="search" placeholder="Search" aria-label="Search"> -->
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
    {% if not properties %}
    <div class="col-12">There are currently no prona active</div>
    <div>{{page.count}}</div> 
      {% else %}
        <div class="album p-5 bg-light"> 
      
         
        <div class="row p-5">
          {% for property in page.object_list %}
          <div class="col-md-4 p-0">
            <div class="card mb-4 box-shadow row">
              {% for image in property.property_image.all %}
                {% if image.is_feature%}
                  <img class="card-img-top img-fluid " src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                {% endif %}
              {% endfor %}
              <a class="text-dark text-decoration-none" href="{{ property.get_absolute_url }}">
                <div class="card-body row">
                  <div class="ps-3">
                   <p class="card-text h4 pt-3">{{  property.title|slice:":50" }}</p>
                  </div>
                  <div class="ps-2 pt-2">
                    {% if property.status %}
                      <i class="fa-solid fa-user"></i><small class="card-text h6 "> {{user.first_name}} {{user.last_name}}  </small>
                    {% else %}
                    <i class="fa-solid fa-user"></i><small class="card-text h6 "> {{user.first_name}} {{user.last_name}}</small> <strong class="h6 text-danger float-end"><i class="fa-solid fa-ban"></i>N/a</strong>
                    {% endif %}
                   </div>
                  <div class="p-2">
                    <i class="fa-solid fa-location-dot"></i><small class="h6 text-muted">  {{property.address_line|slice:":40"}}</small>
                  </div>
                  <div class="p-2">
                    <div class="float-end pe-5">
                      <i class="fa-solid fa-tag"></i><small class="h5 text-muted">  {{property.price}} $</small>
                    </div>
                  </div>

                    <div class="card-footer row">
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-aspect-ratio" viewBox="0 0 16 16">
                          <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h13A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 12.5v-9zM1.5 3a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-13z"/>
                          <path d="M2 4.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1H3v2.5a.5.5 0 0 1-1 0v-3zm12 7a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1 0-1H13V8.5a.5.5 0 0 1 1 0v3z"/>
                        </svg>
                      <small>{{property.area}} m<sup>2</sup></small>
                      </div>

                      {% if property.apartment.room_num or property.apartment.room_num == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bed"></i>   
                          <small>{{ property.apartment.room_num }}</small>
                        </div>
                      
                      {% elif property.villa.room_num or property.villa.room_num == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bed"></i>   
                          <small>{{ property.villa.room_num }}</small>
                        </div>
                      {% else %}
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                        <i class="fa-solid fa-bed"></i>   
                        <small>--</small>
                      </div>
                      {% endif %}
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4" style="text-align: center;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                          <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                          <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                        </svg> <small>{{ property.views }}</small>
                      </div>
                      {% if property.apartment.bath_num == 0 or property.apartment.bath_num%}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bath"></i>  
                          <small>{{ property.apartment.bath_num }}</small>
                        </div>

                      {% elif property.store.bath_num or property.store.bath_num == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bath"></i>  
                          <small>{{ property.store.bath_num }}</small>
                        </div>
                      {% elif property.villa.bath_num or property.villa.bath_num == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bath"></i>  
                          <small>{{ property.villa.bath_num }}</small>
                        </div>
                      {% else %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-bath"></i>  
                          <small>--</small>
                        </div>
                      {% endif%}
                      
                      {% if property.apartment.floor or property.apartment.floor == 0 %}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-arrow-right-to-city"></i>
                          <small>{{ property.apartment.floor }}</small>
                        </div>
                      {% elif property.garage.floor or property.garage.floor == 0%}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-arrow-right-to-city"></i>
                          <small>{{ property.garage.floor }}</small>
                        </div>
                      {% elif  property.store.floor or  property.store.floor == 0%}
                        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                          <i class="fa-solid fa-arrow-right-to-city"></i>
                          <small>{{ property.store.floor }}</small>
                        </div>
                      {% else %}
                      <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 FutureInfo col-4">
                        <i class="fa-solid fa-arrow-right-to-city"></i>
                        <small>--</small>
                      </div>
                      {% endif %}
                      
                      </div>
               </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

      </div>
        {% endif %}
      </div>
<!-- 
        <nav aria-label="...">
          <ul class="pagination">
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active">
              <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
            </li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#">Next</a>
            </li>
          </ul>
        </nav> -->

        
<!-- <div class="container-fluid">
  {% load crispy_forms_tags %}
  <form class="d-flex justify-content-evenly" method="get" action="{% url 'pronat:properties_list' %}">
    {{myFilter.form|crispy}}
     <input class="form-control me-2" name = "q" type="search" placeholder="Search" aria-label="Search"> 
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
  </div> -->

        <nav aria-label="...">
          <ul class="pagination">

        
          {% if page.has_previous %}
          <li class="page-item">
          <a class="page-link" href="{% url 'pronat:properties_list' %}?page={{ page.previous_page_number }}">Previous</a></li>
          {% endif %}

          {% for i in num_pages %}
          <li class="page-item">
            <a class="page-link" href="{% url 'pronat:properties_list' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
          {% endfor %}
          
          {% if page.has_next %}
          <li class="page-item">
          <a class="page-link" href="{% url 'pronat:properties_list' %}?page={{ page.next_page_number }}">Next</a></li>
          {% endif %}            
        </ul>
      </nav>

    {%endblock %}
   

templates/home/team.html
{% extends '../base.html' %}
{% load static %}
{%block css %}

<link href="{% static 'core/css/ourteam.css' %}" rel="stylesheet">

{%endblock%}
{% block content %}

<div class="container">
    <div class="row">
        <h1>Our Team</h1>
    </div>
    {% for agent in agents %}
      <div class="row featurette">
          <div class="col-md-7">
              <h2 class="featurette-heading">{{agent.first_name}}  <span class="text-muted">{{agent.last_name}}</span></h2>
              <div class="row">
                  <div class="col-md-5">
                      <i class="fa-solid fa-phone h1"></i><small class="h3">Phone:</small>
                      <small class="h3">{{agent.mobile}}</small>
                  </div>
                  <div class="col-md-5">
                      <i class="fa-solid fa-phone h1"></i><small class="h3">Email:</small>
                      <small class="h3">{{agent.email}}</small>
                  </div>
                  <div class="col-md-5">
                    <ul>
                      
                    </ul>
                  </div> 
              </div>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="img-fluid w-100" src="media/{{agent.image}}" alt="{{agent.alt_text}}">
    
          </div>
        </div>
      {%endfor%}

</div>
{%endblock%}