agent/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('search/<slug:slug>/', views.agent_properties, name='agent_properties'),
    path('ourteam/', views.agent_all, name='agent_all'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('property.urls', namespace='property')),
    path('agent', include('agent.urls', namespace='agent')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'pronat'

urlpatterns = [
    path('', views.properties_all, name="home_page"),
    path('properties', views.properties_list, name="properties_list"),
    path('property/<slug:slug>', views.property_detail, name = "property_detail"),
    path('apartment', views.apartment_all, name="apartment_all"),
    path('land', views.land_all, name="land_all"),
    path('garage', views.garage_all, name="garage_all"),
    path('store', views.store_all, name="store_all"),
    path('villa', views.villa_all, name="villa_all"),
    path('contact', views.contact_page,name="contact_page"),
    path('about', views.aboutus,name="aboutus"),
    path('politikat', views.politikat_privatesise,name="politkat"),
    path('zyrat', views.ofice, name="zyrat"),
    path('team',views.team, name="teams"),
]

templates/base.html
<!DOCTYPE html>
{%load static%}
<head>
    <meta charset="utf-8" />
    <title>{% block title %}Realestateal{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" 
    integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
   
   
   
    <link rel="stylesheet" href="{% static 'core/css/base2.css' %}">

    <link rel="stylesheet" href="{% static 'owl_carousel/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'owl_carousel/owl.theme.default.css' %}">
   

    {% block css%}   
    {% endblock%}
    

  </head>
    <body>
        
        <nav class="navbar">
            <div class="brand-title">
                <a class="navbar-brand" href="{% url "property:home_page" %}"> <img src="{% static 'images/logo.png' %}"></a>
            </div>
            <a href="#" class="toggle-button">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </a>
            <div class="navbar-links">
                <ul>
                    <li><a href="{% url "property:home_page" %}">Home</a></li>
                    <li><a href="{% url "property:properties_list" %}">Properties</a></li>
                    <li><a href="{% url "property:contact_page" %}">Contact Us</a></li>
                    <li><a href="{% url "agent:agent_all" %}">Our Team</a></li>
                    
                    
                </ul>
            </div>
        </nav>
        <script src="{% static 'js/prova.js' %}" defer></script>
        {% block content %}
    
        {%endblock%}
    <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-col">
                        <h4>Links</h4>
                        <ul>
                            <li><a href="{% url "property:home_page" %}">Home</a></li>
                            <li><a href="{% url "property:aboutus" %}">About Us</a></li>
                            <li><a href="{% url "property:zyrat" %}">Zyrat</a></li>
                            <li><a href="{% url "property:politkat" %}">Politikat e privatesise</a></li>
                        </ul>
                    </div>
                    <div class="footer-col">
                        <h4>Properties</h4>
                        <ul>
                            <li><a href="{% url "property:apartment_all" %}">Apartamentet</a></li>
                            <li><a href="{% url "property:villa_all" %}">Villa</a></li>
                            <li><a href="{% url "property:store_all" %}">Store</a></li>
                            <li><a href="{% url "property:land_all" %}">Land</a></li>
                            <li><a href="{% url "property:garage_all" %}">Garage</a></li>
                        </ul>
                    </div>
                    <div class="footer-col">
                        <h4>About</h4>
                        <ul>
                            
                            <li><a href="{% url "property:contact_page" %}"><i class="fa-solid fa-phone"></i> +355 67 300 5050</a></li>
                            <li><a href="{% url "property:contact_page" %}"><i class="fa-solid fa-at"></i> info@dominusoft.co</a></li>
                            <li><a href="{% url "property:contact_page" %}"><i class="fa-solid fa-location-dot"></i> Rr: “Myslym Shyri”, Tiranë</a></li>
                            <li><a href="{% url "property:contact_page" %}"><i class="fa-solid fa-copyright"></i> Dominusoft</a></li>
               
                        </ul>
                    </div>
                    <div class="footer-col">
                        
                        <h4>follow us</h4>
                        

                        <div class="social-links">
                            
                            <a href="https://www.facebook.com/DominusoftTrainings" target="_blank"><i class="fab fa-facebook-f"></i></a>
                            <a href="https://www.youtube.com/channel/UCfA_aPAQ4v6EUgRWfFq-F-g" target="_blank"><i class="fab fa-youtube"></i></a>
                            <a href="https://www.instagram.com/dominusoft_trainings" target="_blank"><i class="fab fa-instagram"></i></a>
                            <a href="https://www.linkedin.com/in/dominusoft-training-531714151" target="_blank"><i class="fab fa-linkedin-in"></i></a> 
                            
                        </div>
                        <div class="image">
                            <a class="navbar-brand" href="{% url "property:home_page" %}"> <img src="{% static 'images/logo.png' %}"></a>
                        </div>
                    </div>
                </div>
            </div>
           
    </footer>
       <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" 
       integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
       <script src="https://code.jquery.com/jquery-3.6.0.js" 
       integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
       <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" 
       integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" 
       integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
       <script src="{% static 'owl_carousel/owl.carousel.js' %}"></script>
       <script src="{% static 'js/scripts.js' %}"></script>

    </body>


</html>